#include "RegisterMonoModules.h"

extern bool gEnableGyroscope;

extern "C"
{
	typedef void* gpointer;
	typedef int gboolean;
#if !(TARGET_IPHONE_SIMULATOR)
	const char*			UnityIPhoneRuntimeVersion = "3.5.2f2";
	void				mono_dl_register_symbol (const char* name, void *addr);
	extern int 			mono_ficall_flag;
	void				mono_aot_register_module(gpointer *aot_info);
	extern gboolean		mono_aot_only;
	extern gpointer*	mono_aot_module_Antares_QRCode_info; // Antares.QRCode.dll
	extern gpointer*	mono_aot_module_Assembly_CSharp_firstpass_info; // Assembly-CSharp-firstpass.dll
	extern gpointer*	mono_aot_module_Assembly_CSharp_info; // Assembly-CSharp.dll
	extern gpointer*	mono_aot_module_Assembly_UnityScript_info; // Assembly-UnityScript.dll
	extern gpointer*	mono_aot_module_Boo_Lang_info; // Boo.Lang.dll
	extern gpointer*	mono_aot_module_System_Core_info; // System.Core.dll
	extern gpointer*	mono_aot_module_System_info; // System.dll
	extern gpointer*	mono_aot_module_UnityEngine_info; // UnityEngine.dll
	extern gpointer*	mono_aot_module_UnityScript_Lang_info; // UnityScript.Lang.dll
	extern gpointer*	mono_aot_module_mscorlib_info; // mscorlib.dll
#endif // !(TARGET_IPHONE_SIMULATOR)
	void	_arIsCaptureAvailable();
	void	_arStartCameraCapture();
	void	_arStopCameraCapture();
	void	_arSetExposureMode();
	void	_arSetFocusMode();
	void	_arStartVideoTexturePlayback();
	void	_arPauseVideoTexturePlayback();
	void	_arUnpauseVideoTexturePlayback();
	void	_arStopVideoTexturePlayback();
}
void RegisterMonoModules()
{
    gEnableGyroscope = false;
#if !(TARGET_IPHONE_SIMULATOR)
	mono_aot_only = true;
	mono_ficall_flag = false;
	mono_aot_register_module(mono_aot_module_Antares_QRCode_info);
	mono_aot_register_module(mono_aot_module_Assembly_CSharp_firstpass_info);
	mono_aot_register_module(mono_aot_module_Assembly_CSharp_info);
	mono_aot_register_module(mono_aot_module_Assembly_UnityScript_info);
	mono_aot_register_module(mono_aot_module_Boo_Lang_info);
	mono_aot_register_module(mono_aot_module_System_Core_info);
	mono_aot_register_module(mono_aot_module_System_info);
	mono_aot_register_module(mono_aot_module_UnityEngine_info);
	mono_aot_register_module(mono_aot_module_UnityScript_Lang_info);
	mono_aot_register_module(mono_aot_module_mscorlib_info);

	mono_dl_register_symbol("_arIsCaptureAvailable", (void*)&_arIsCaptureAvailable);
	mono_dl_register_symbol("_arStartCameraCapture", (void*)&_arStartCameraCapture);
	mono_dl_register_symbol("_arStopCameraCapture", (void*)&_arStopCameraCapture);
	mono_dl_register_symbol("_arSetExposureMode", (void*)&_arSetExposureMode);
	mono_dl_register_symbol("_arSetFocusMode", (void*)&_arSetFocusMode);
	mono_dl_register_symbol("_arStartVideoTexturePlayback", (void*)&_arStartVideoTexturePlayback);
	mono_dl_register_symbol("_arPauseVideoTexturePlayback", (void*)&_arPauseVideoTexturePlayback);
	mono_dl_register_symbol("_arUnpauseVideoTexturePlayback", (void*)&_arUnpauseVideoTexturePlayback);
	mono_dl_register_symbol("_arStopVideoTexturePlayback", (void*)&_arStopVideoTexturePlayback);
#endif // !(TARGET_IPHONE_SIMULATOR)
}

void RegisterAllStrippedInternalCalls ()
{
	void Register_UnityEngine_Animation_get_clip ();
	Register_UnityEngine_Animation_get_clip ();
	void Register_UnityEngine_Animation_set_wrapMode ();
	Register_UnityEngine_Animation_set_wrapMode ();
	void Register_UnityEngine_Animation_get_isPlaying ();
	Register_UnityEngine_Animation_get_isPlaying ();
	void Register_UnityEngine_Animation_IsPlaying ();
	Register_UnityEngine_Animation_IsPlaying ();
	void Register_UnityEngine_Animation_Play ();
	Register_UnityEngine_Animation_Play ();
	void Register_UnityEngine_Animation_CrossFade ();
	Register_UnityEngine_Animation_CrossFade ();
	void Register_UnityEngine_Animation_GetClipCount ();
	Register_UnityEngine_Animation_GetClipCount ();
	void Register_UnityEngine_Animation_PlayDefaultAnimation ();
	Register_UnityEngine_Animation_PlayDefaultAnimation ();
	void Register_UnityEngine_Animation_GetState ();
	Register_UnityEngine_Animation_GetState ();
	void Register_UnityEngine_Animation_GetStateAtIndex ();
	Register_UnityEngine_Animation_GetStateAtIndex ();
	void Register_UnityEngine_Animation_GetStateCount ();
	Register_UnityEngine_Animation_GetStateCount ();
	void Register_UnityEngine_AnimationCurve_Cleanup ();
	Register_UnityEngine_AnimationCurve_Cleanup ();
	void Register_UnityEngine_AnimationCurve_Evaluate ();
	Register_UnityEngine_AnimationCurve_Evaluate ();
	void Register_UnityEngine_AnimationCurve_AddKey ();
	Register_UnityEngine_AnimationCurve_AddKey ();
	void Register_UnityEngine_AnimationCurve_INTERNAL_CALL_AddKey_Internal ();
	Register_UnityEngine_AnimationCurve_INTERNAL_CALL_AddKey_Internal ();
	void Register_UnityEngine_AnimationCurve_INTERNAL_CALL_MoveKey ();
	Register_UnityEngine_AnimationCurve_INTERNAL_CALL_MoveKey ();
	void Register_UnityEngine_AnimationCurve_RemoveKey ();
	Register_UnityEngine_AnimationCurve_RemoveKey ();
	void Register_UnityEngine_AnimationCurve_get_length ();
	Register_UnityEngine_AnimationCurve_get_length ();
	void Register_UnityEngine_AnimationCurve_SetKeys ();
	Register_UnityEngine_AnimationCurve_SetKeys ();
	void Register_UnityEngine_AnimationCurve_GetKey_Internal ();
	Register_UnityEngine_AnimationCurve_GetKey_Internal ();
	void Register_UnityEngine_AnimationCurve_GetKeys ();
	Register_UnityEngine_AnimationCurve_GetKeys ();
	void Register_UnityEngine_AnimationCurve_SmoothTangents ();
	Register_UnityEngine_AnimationCurve_SmoothTangents ();
	void Register_UnityEngine_AnimationCurve_get_preWrapMode ();
	Register_UnityEngine_AnimationCurve_get_preWrapMode ();
	void Register_UnityEngine_AnimationCurve_set_preWrapMode ();
	Register_UnityEngine_AnimationCurve_set_preWrapMode ();
	void Register_UnityEngine_AnimationCurve_get_postWrapMode ();
	Register_UnityEngine_AnimationCurve_get_postWrapMode ();
	void Register_UnityEngine_AnimationCurve_set_postWrapMode ();
	Register_UnityEngine_AnimationCurve_set_postWrapMode ();
	void Register_UnityEngine_AnimationCurve_Init ();
	Register_UnityEngine_AnimationCurve_Init ();
	void Register_UnityEngine_AnimationEvent_Destroy ();
	Register_UnityEngine_AnimationEvent_Destroy ();
	void Register_UnityEngine_AnimationState_set_wrapMode ();
	Register_UnityEngine_AnimationState_set_wrapMode ();
	void Register_UnityEngine_AnimationState_get_time ();
	Register_UnityEngine_AnimationState_get_time ();
	void Register_UnityEngine_AnimationState_get_normalizedTime ();
	Register_UnityEngine_AnimationState_get_normalizedTime ();
	void Register_UnityEngine_AnimationState_set_speed ();
	Register_UnityEngine_AnimationState_set_speed ();
	void Register_UnityEngine_AnimationState_get_length ();
	Register_UnityEngine_AnimationState_get_length ();
	void Register_UnityEngine_AnimationState_get_name ();
	Register_UnityEngine_AnimationState_get_name ();
	void Register_UnityEngine_Application_Quit ();
	Register_UnityEngine_Application_Quit ();
	void Register_UnityEngine_Application_CancelQuit ();
	Register_UnityEngine_Application_CancelQuit ();
	void Register_UnityEngine_Application_get_loadedLevel ();
	Register_UnityEngine_Application_get_loadedLevel ();
	void Register_UnityEngine_Application_get_loadedLevelName ();
	Register_UnityEngine_Application_get_loadedLevelName ();
	void Register_UnityEngine_Application_LoadLevelAsync ();
	Register_UnityEngine_Application_LoadLevelAsync ();
	void Register_UnityEngine_Application_get_isLoadingLevel ();
	Register_UnityEngine_Application_get_isLoadingLevel ();
	void Register_UnityEngine_Application_get_levelCount ();
	Register_UnityEngine_Application_get_levelCount ();
	void Register_UnityEngine_Application_GetStreamProgressForLevelByName ();
	Register_UnityEngine_Application_GetStreamProgressForLevelByName ();
	void Register_UnityEngine_Application_GetStreamProgressForLevel ();
	Register_UnityEngine_Application_GetStreamProgressForLevel ();
	void Register_UnityEngine_Application_get_streamedBytes ();
	Register_UnityEngine_Application_get_streamedBytes ();
	void Register_UnityEngine_Application_CanStreamedLevelBeLoadedByName ();
	Register_UnityEngine_Application_CanStreamedLevelBeLoadedByName ();
	void Register_UnityEngine_Application_CanStreamedLevelBeLoaded ();
	Register_UnityEngine_Application_CanStreamedLevelBeLoaded ();
	void Register_UnityEngine_Application_get_isPlaying ();
	Register_UnityEngine_Application_get_isPlaying ();
	void Register_UnityEngine_Application_get_isEditor ();
	Register_UnityEngine_Application_get_isEditor ();
	void Register_UnityEngine_Application_get_isWebPlayer ();
	Register_UnityEngine_Application_get_isWebPlayer ();
	void Register_UnityEngine_Application_get_platform ();
	Register_UnityEngine_Application_get_platform ();
	void Register_UnityEngine_Application_CaptureScreenshot ();
	Register_UnityEngine_Application_CaptureScreenshot ();
	void Register_UnityEngine_Application_get_runInBackground ();
	Register_UnityEngine_Application_get_runInBackground ();
	void Register_UnityEngine_Application_set_runInBackground ();
	Register_UnityEngine_Application_set_runInBackground ();
	void Register_UnityEngine_Application_HasProLicense ();
	Register_UnityEngine_Application_HasProLicense ();
	void Register_UnityEngine_Application_HasAdvancedLicense ();
	Register_UnityEngine_Application_HasAdvancedLicense ();
	void Register_UnityEngine_Application_DontDestroyOnLoad ();
	Register_UnityEngine_Application_DontDestroyOnLoad ();
	void Register_UnityEngine_Application_get_dataPath ();
	Register_UnityEngine_Application_get_dataPath ();
	void Register_UnityEngine_Application_get_streamingAssetsPath ();
	Register_UnityEngine_Application_get_streamingAssetsPath ();
	void Register_UnityEngine_Application_get_persistentDataPath ();
	Register_UnityEngine_Application_get_persistentDataPath ();
	void Register_UnityEngine_Application_get_temporaryCachePath ();
	Register_UnityEngine_Application_get_temporaryCachePath ();
	void Register_UnityEngine_Application_get_srcValue ();
	Register_UnityEngine_Application_get_srcValue ();
	void Register_UnityEngine_Application_get_absoluteURL ();
	Register_UnityEngine_Application_get_absoluteURL ();
	void Register_UnityEngine_Application_Internal_ExternalCall ();
	Register_UnityEngine_Application_Internal_ExternalCall ();
	void Register_UnityEngine_Application_get_unityVersion ();
	Register_UnityEngine_Application_get_unityVersion ();
	void Register_UnityEngine_Application_GetBuildUnityVersion ();
	Register_UnityEngine_Application_GetBuildUnityVersion ();
	void Register_UnityEngine_Application_GetNumericUnityVersion ();
	Register_UnityEngine_Application_GetNumericUnityVersion ();
	void Register_UnityEngine_Application_get_webSecurityEnabled ();
	Register_UnityEngine_Application_get_webSecurityEnabled ();
	void Register_UnityEngine_Application_get_webSecurityHostUrl ();
	Register_UnityEngine_Application_get_webSecurityHostUrl ();
	void Register_UnityEngine_Application_OpenURL ();
	Register_UnityEngine_Application_OpenURL ();
	void Register_UnityEngine_Application_CommitSuicide ();
	Register_UnityEngine_Application_CommitSuicide ();
	void Register_UnityEngine_Application_get_targetFrameRate ();
	Register_UnityEngine_Application_get_targetFrameRate ();
	void Register_UnityEngine_Application_set_targetFrameRate ();
	Register_UnityEngine_Application_set_targetFrameRate ();
	void Register_UnityEngine_Application_get_systemLanguage ();
	Register_UnityEngine_Application_get_systemLanguage ();
	void Register_UnityEngine_Application_SetLogCallbackDefined ();
	Register_UnityEngine_Application_SetLogCallbackDefined ();
	void Register_UnityEngine_Application_get_backgroundLoadingPriority ();
	Register_UnityEngine_Application_get_backgroundLoadingPriority ();
	void Register_UnityEngine_Application_set_backgroundLoadingPriority ();
	Register_UnityEngine_Application_set_backgroundLoadingPriority ();
	void Register_UnityEngine_Application_get_internetReachability ();
	Register_UnityEngine_Application_get_internetReachability ();
	void Register_UnityEngine_Application_get_genuine ();
	Register_UnityEngine_Application_get_genuine ();
	void Register_UnityEngine_Application_get_genuineCheckAvailable ();
	Register_UnityEngine_Application_get_genuineCheckAvailable ();
	void Register_UnityEngine_Application_RequestUserAuthorization ();
	Register_UnityEngine_Application_RequestUserAuthorization ();
	void Register_UnityEngine_Application_HasUserAuthorization ();
	Register_UnityEngine_Application_HasUserAuthorization ();
	void Register_UnityEngine_Application_ReplyToUserAuthorizationRequest ();
	Register_UnityEngine_Application_ReplyToUserAuthorizationRequest ();
	void Register_UnityEngine_Application_GetUserAuthorizationRequestMode_Internal ();
	Register_UnityEngine_Application_GetUserAuthorizationRequestMode_Internal ();
	void Register_UnityEngine_AssetBundleCreateRequest_get_assetBundle ();
	Register_UnityEngine_AssetBundleCreateRequest_get_assetBundle ();
	void Register_UnityEngine_AsyncOperation_InternalDestroy ();
	Register_UnityEngine_AsyncOperation_InternalDestroy ();
	void Register_UnityEngine_AudioClip_get_length ();
	Register_UnityEngine_AudioClip_get_length ();
	void Register_UnityEngine_AudioClip_get_samples ();
	Register_UnityEngine_AudioClip_get_samples ();
	void Register_UnityEngine_AudioClip_get_channels ();
	Register_UnityEngine_AudioClip_get_channels ();
	void Register_UnityEngine_AudioClip_get_frequency ();
	Register_UnityEngine_AudioClip_get_frequency ();
	void Register_UnityEngine_AudioClip_get_isReadyToPlay ();
	Register_UnityEngine_AudioClip_get_isReadyToPlay ();
	void Register_UnityEngine_AudioClip_GetData ();
	Register_UnityEngine_AudioClip_GetData ();
	void Register_UnityEngine_AudioClip_SetData ();
	Register_UnityEngine_AudioClip_SetData ();
	void Register_UnityEngine_AudioClip_Construct_Internal ();
	Register_UnityEngine_AudioClip_Construct_Internal ();
	void Register_UnityEngine_AudioClip_Init_Internal ();
	Register_UnityEngine_AudioClip_Init_Internal ();
	void Register_UnityEngine_AudioSource_set_volume ();
	Register_UnityEngine_AudioSource_set_volume ();
	void Register_UnityEngine_AudioSource_set_clip ();
	Register_UnityEngine_AudioSource_set_clip ();
	void Register_UnityEngine_AudioSource_Play ();
	Register_UnityEngine_AudioSource_Play ();
	void Register_UnityEngine_AudioSource_PlayOneShot ();
	Register_UnityEngine_AudioSource_PlayOneShot ();
	void Register_UnityEngine_AudioSource_set_mute ();
	Register_UnityEngine_AudioSource_set_mute ();
	void Register_UnityEngine_Behaviour_set_enabled ();
	Register_UnityEngine_Behaviour_set_enabled ();
	void Register_UnityEngine_Camera_get_nearClipPlane ();
	Register_UnityEngine_Camera_get_nearClipPlane ();
	void Register_UnityEngine_Camera_set_nearClipPlane ();
	Register_UnityEngine_Camera_set_nearClipPlane ();
	void Register_UnityEngine_Camera_set_farClipPlane ();
	Register_UnityEngine_Camera_set_farClipPlane ();
	void Register_UnityEngine_Camera_set_orthographicSize ();
	Register_UnityEngine_Camera_set_orthographicSize ();
	void Register_UnityEngine_Camera_set_orthographic ();
	Register_UnityEngine_Camera_set_orthographic ();
	void Register_UnityEngine_Camera_set_depth ();
	Register_UnityEngine_Camera_set_depth ();
	void Register_UnityEngine_Camera_set_cullingMask ();
	Register_UnityEngine_Camera_set_cullingMask ();
	void Register_UnityEngine_Camera_INTERNAL_get_rect ();
	Register_UnityEngine_Camera_INTERNAL_get_rect ();
	void Register_UnityEngine_Camera_INTERNAL_set_rect ();
	Register_UnityEngine_Camera_INTERNAL_set_rect ();
	void Register_UnityEngine_Camera_set_targetTexture ();
	Register_UnityEngine_Camera_set_targetTexture ();
	void Register_UnityEngine_Camera_set_clearFlags ();
	Register_UnityEngine_Camera_set_clearFlags ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_ScreenToWorldPoint ();
	Register_UnityEngine_Camera_INTERNAL_CALL_ScreenToWorldPoint ();
	void Register_UnityEngine_Camera_INTERNAL_CALL_ScreenPointToRay ();
	Register_UnityEngine_Camera_INTERNAL_CALL_ScreenPointToRay ();
	void Register_UnityEngine_Camera_get_main ();
	Register_UnityEngine_Camera_get_main ();
	void Register_UnityEngine_Camera_Render ();
	Register_UnityEngine_Camera_Render ();
	void Register_UnityEngine_Collider_get_attachedRigidbody ();
	Register_UnityEngine_Collider_get_attachedRigidbody ();
	void Register_UnityEngine_Component_get_transform ();
	Register_UnityEngine_Component_get_transform ();
	void Register_UnityEngine_Component_get_camera ();
	Register_UnityEngine_Component_get_camera ();
	void Register_UnityEngine_Component_get_renderer ();
	Register_UnityEngine_Component_get_renderer ();
	void Register_UnityEngine_Component_get_guiText ();
	Register_UnityEngine_Component_get_guiText ();
	void Register_UnityEngine_Component_get_gameObject ();
	Register_UnityEngine_Component_get_gameObject ();
	void Register_UnityEngine_Component_GetComponent ();
	Register_UnityEngine_Component_GetComponent ();
	void Register_UnityEngine_Component_set_active ();
	Register_UnityEngine_Component_set_active ();
	void Register_UnityEngine_Component_CompareTag ();
	Register_UnityEngine_Component_CompareTag ();
	void Register_UnityEngine_Coroutine_ReleaseCoroutine ();
	Register_UnityEngine_Coroutine_ReleaseCoroutine ();
	void Register_UnityEngine_Debug_Internal_Log ();
	Register_UnityEngine_Debug_Internal_Log ();
	void Register_UnityEngine_GameObject_CreatePrimitive ();
	Register_UnityEngine_GameObject_CreatePrimitive ();
	void Register_UnityEngine_GameObject_GetComponent ();
	Register_UnityEngine_GameObject_GetComponent ();
	void Register_UnityEngine_GameObject_GetComponentByName ();
	Register_UnityEngine_GameObject_GetComponentByName ();
	void Register_UnityEngine_GameObject_get_isStatic ();
	Register_UnityEngine_GameObject_get_isStatic ();
	void Register_UnityEngine_GameObject_set_isStatic ();
	Register_UnityEngine_GameObject_set_isStatic ();
	void Register_UnityEngine_GameObject_get_isStaticBatchable ();
	Register_UnityEngine_GameObject_get_isStaticBatchable ();
	void Register_UnityEngine_GameObject_GetComponentsInternal ();
	Register_UnityEngine_GameObject_GetComponentsInternal ();
	void Register_UnityEngine_GameObject_get_transform ();
	Register_UnityEngine_GameObject_get_transform ();
	void Register_UnityEngine_GameObject_get_rigidbody ();
	Register_UnityEngine_GameObject_get_rigidbody ();
	void Register_UnityEngine_GameObject_get_camera ();
	Register_UnityEngine_GameObject_get_camera ();
	void Register_UnityEngine_GameObject_get_light ();
	Register_UnityEngine_GameObject_get_light ();
	void Register_UnityEngine_GameObject_get_animation ();
	Register_UnityEngine_GameObject_get_animation ();
	void Register_UnityEngine_GameObject_get_constantForce ();
	Register_UnityEngine_GameObject_get_constantForce ();
	void Register_UnityEngine_GameObject_get_renderer ();
	Register_UnityEngine_GameObject_get_renderer ();
	void Register_UnityEngine_GameObject_get_audio ();
	Register_UnityEngine_GameObject_get_audio ();
	void Register_UnityEngine_GameObject_get_guiText ();
	Register_UnityEngine_GameObject_get_guiText ();
	void Register_UnityEngine_GameObject_get_networkView ();
	Register_UnityEngine_GameObject_get_networkView ();
	void Register_UnityEngine_GameObject_get_guiElement ();
	Register_UnityEngine_GameObject_get_guiElement ();
	void Register_UnityEngine_GameObject_get_guiTexture ();
	Register_UnityEngine_GameObject_get_guiTexture ();
	void Register_UnityEngine_GameObject_get_collider ();
	Register_UnityEngine_GameObject_get_collider ();
	void Register_UnityEngine_GameObject_get_hingeJoint ();
	Register_UnityEngine_GameObject_get_hingeJoint ();
	void Register_UnityEngine_GameObject_get_particleEmitter ();
	Register_UnityEngine_GameObject_get_particleEmitter ();
	void Register_UnityEngine_GameObject_get_layer ();
	Register_UnityEngine_GameObject_get_layer ();
	void Register_UnityEngine_GameObject_set_layer ();
	Register_UnityEngine_GameObject_set_layer ();
	void Register_UnityEngine_GameObject_get_active ();
	Register_UnityEngine_GameObject_get_active ();
	void Register_UnityEngine_GameObject_set_active ();
	Register_UnityEngine_GameObject_set_active ();
	void Register_UnityEngine_GameObject_SetActiveRecursively ();
	Register_UnityEngine_GameObject_SetActiveRecursively ();
	void Register_UnityEngine_GameObject_get_tag ();
	Register_UnityEngine_GameObject_get_tag ();
	void Register_UnityEngine_GameObject_set_tag ();
	Register_UnityEngine_GameObject_set_tag ();
	void Register_UnityEngine_GameObject_CompareTag ();
	Register_UnityEngine_GameObject_CompareTag ();
	void Register_UnityEngine_GameObject_FindGameObjectWithTag ();
	Register_UnityEngine_GameObject_FindGameObjectWithTag ();
	void Register_UnityEngine_GameObject_FindGameObjectsWithTag ();
	Register_UnityEngine_GameObject_FindGameObjectsWithTag ();
	void Register_UnityEngine_GameObject_SendMessageUpwards ();
	Register_UnityEngine_GameObject_SendMessageUpwards ();
	void Register_UnityEngine_GameObject_SendMessage ();
	Register_UnityEngine_GameObject_SendMessage ();
	void Register_UnityEngine_GameObject_BroadcastMessage ();
	Register_UnityEngine_GameObject_BroadcastMessage ();
	void Register_UnityEngine_GameObject_AddComponent ();
	Register_UnityEngine_GameObject_AddComponent ();
	void Register_UnityEngine_GameObject_Internal_AddComponentWithType ();
	Register_UnityEngine_GameObject_Internal_AddComponentWithType ();
	void Register_UnityEngine_GameObject_Internal_CreateGameObject ();
	Register_UnityEngine_GameObject_Internal_CreateGameObject ();
	void Register_UnityEngine_GameObject_SampleAnimation ();
	Register_UnityEngine_GameObject_SampleAnimation ();
	void Register_UnityEngine_GameObject_PlayAnimation ();
	Register_UnityEngine_GameObject_PlayAnimation ();
	void Register_UnityEngine_GameObject_StopAnimation ();
	Register_UnityEngine_GameObject_StopAnimation ();
	void Register_UnityEngine_GameObject_Find ();
	Register_UnityEngine_GameObject_Find ();
	void Register_UnityEngine_Graphics_DrawTexture ();
	Register_UnityEngine_Graphics_DrawTexture ();
	void Register_UnityEngine_GUI_INTERNAL_CALL_Internal_UpdateColors ();
	Register_UnityEngine_GUI_INTERNAL_CALL_Internal_UpdateColors ();
	void Register_UnityEngine_GUI_Internal_SetEnabled ();
	Register_UnityEngine_GUI_Internal_SetEnabled ();
	void Register_UnityEngine_GUI_get_depth ();
	Register_UnityEngine_GUI_get_depth ();
	void Register_UnityEngine_GUI_set_depth ();
	Register_UnityEngine_GUI_set_depth ();
	void Register_UnityEngine_GUI_InitializeGUIClipTexture ();
	Register_UnityEngine_GUI_InitializeGUIClipTexture ();
	void Register_UnityEngine_GUI_get_blendMaterial ();
	Register_UnityEngine_GUI_get_blendMaterial ();
	void Register_UnityEngine_GUI_get_blitMaterial ();
	Register_UnityEngine_GUI_get_blitMaterial ();
	void Register_UnityEngine_GUI_get_usePageScrollbars ();
	Register_UnityEngine_GUI_get_usePageScrollbars ();
	void Register_UnityEngine_GUI_InternalRepaintEditorWindow ();
	Register_UnityEngine_GUI_InternalRepaintEditorWindow ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_Push ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_Push ();
	void Register_UnityEngine_GUIClip_Pop ();
	Register_UnityEngine_GUIClip_Pop ();
	void Register_UnityEngine_GUIClip_get_enabled ();
	Register_UnityEngine_GUIClip_get_enabled ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_Unclip_Vector2_icall ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_Unclip_Vector2_icall ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_Unclip_Rect_icall ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_Unclip_Rect_icall ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_Clip_Vector2_icall ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_Clip_Vector2_icall ();
	void Register_UnityEngine_GUIClip_GetMatrix ();
	Register_UnityEngine_GUIClip_GetMatrix ();
	void Register_UnityEngine_GUIClip_INTERNAL_CALL_SetMatrix ();
	Register_UnityEngine_GUIClip_INTERNAL_CALL_SetMatrix ();
	void Register_UnityEngine_GUIClip_get_visibleRect ();
	Register_UnityEngine_GUIClip_get_visibleRect ();
	void Register_UnityEngine_GUIClip_Begin ();
	Register_UnityEngine_GUIClip_Begin ();
	void Register_UnityEngine_GUIClip_INTERNAL_GetAbsoluteMousePosition ();
	Register_UnityEngine_GUIClip_INTERNAL_GetAbsoluteMousePosition ();
	void Register_UnityEngine_GUIClip_End ();
	Register_UnityEngine_GUIClip_End ();
	void Register_UnityEngine_GUIClip_EndThroughException ();
	Register_UnityEngine_GUIClip_EndThroughException ();
	void Register_UnityEngine_GUISettings_Internal_GetCursorFlashSpeed ();
	Register_UnityEngine_GUISettings_Internal_GetCursorFlashSpeed ();
	void Register_UnityEngine_GUIStyle_Init ();
	Register_UnityEngine_GUIStyle_Init ();
	void Register_UnityEngine_GUIStyle_Cleanup ();
	Register_UnityEngine_GUIStyle_Cleanup ();
	void Register_UnityEngine_GUIStyle_Internal_GetLineHeight ();
	Register_UnityEngine_GUIStyle_Internal_GetLineHeight ();
	void Register_UnityEngine_GUIStyle_Internal_ApplyToCache ();
	Register_UnityEngine_GUIStyle_Internal_ApplyToCache ();
	void Register_UnityEngine_GUIStyle_Internal_Draw ();
	Register_UnityEngine_GUIStyle_Internal_Draw ();
	void Register_UnityEngine_GUIStyle_Internal_AnyTouchesOnScreen ();
	Register_UnityEngine_GUIStyle_Internal_AnyTouchesOnScreen ();
	void Register_UnityEngine_GUIStyle_Internal_GetCursorFlashOffset ();
	Register_UnityEngine_GUIStyle_Internal_GetCursorFlashOffset ();
	void Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_DrawCursor ();
	Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_DrawCursor ();
	void Register_UnityEngine_GUIStyle_Internal_DrawWithTextSelection ();
	Register_UnityEngine_GUIStyle_Internal_DrawWithTextSelection ();
	void Register_UnityEngine_GUIStyle_SetDefaultFont ();
	Register_UnityEngine_GUIStyle_SetDefaultFont ();
	void Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorPixelPosition ();
	Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorPixelPosition ();
	void Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorStringIndex ();
	Register_UnityEngine_GUIStyle_INTERNAL_CALL_Internal_GetCursorStringIndex ();
	void Register_UnityEngine_GUIStyle_Internal_CalcSize ();
	Register_UnityEngine_GUIStyle_Internal_CalcSize ();
	void Register_UnityEngine_GUIStyle_Internal_CalcHeight ();
	Register_UnityEngine_GUIStyle_Internal_CalcHeight ();
	void Register_UnityEngine_GUIStyle_Internal_CalcMinMaxWidth ();
	Register_UnityEngine_GUIStyle_Internal_CalcMinMaxWidth ();
	void Register_UnityEngine_GUIText_set_text ();
	Register_UnityEngine_GUIText_set_text ();
	void Register_UnityEngine_GUIText_get_material ();
	Register_UnityEngine_GUIText_get_material ();
	void Register_UnityEngine_GUIUtility_UpdateUndoName ();
	Register_UnityEngine_GUIUtility_UpdateUndoName ();
	void Register_UnityEngine_GUIUtility_SetDidGUIWindowsEatLastEvent ();
	Register_UnityEngine_GUIUtility_SetDidGUIWindowsEatLastEvent ();
	void Register_UnityEngine_GUIUtility_get_systemCopyBuffer ();
	Register_UnityEngine_GUIUtility_get_systemCopyBuffer ();
	void Register_UnityEngine_GUIUtility_set_systemCopyBuffer ();
	Register_UnityEngine_GUIUtility_set_systemCopyBuffer ();
	void Register_UnityEngine_GUIUtility_Internal_LoadSkin ();
	Register_UnityEngine_GUIUtility_Internal_LoadSkin ();
	void Register_UnityEngine_GUIUtility_Internal_ExitGUI ();
	Register_UnityEngine_GUIUtility_Internal_ExitGUI ();
	void Register_UnityEngine_GUIUtility_GetInGameWindowsIDList ();
	Register_UnityEngine_GUIUtility_GetInGameWindowsIDList ();
	void Register_UnityEngine_GUIUtility_SetHasKeyboardControl ();
	Register_UnityEngine_GUIUtility_SetHasKeyboardControl ();
	void Register_UnityEngine_GUIUtility_SetKeyboardDirection ();
	Register_UnityEngine_GUIUtility_SetKeyboardDirection ();
	void Register_UnityEngine_GUIUtility_GetKeyboardDirection ();
	Register_UnityEngine_GUIUtility_GetKeyboardDirection ();
	void Register_UnityEngine_GUIUtility_CurrentScriptHasKeyboardFocus ();
	Register_UnityEngine_GUIUtility_CurrentScriptHasKeyboardFocus ();
	void Register_UnityEngine_GUIUtility_GetMouseUsed ();
	Register_UnityEngine_GUIUtility_GetMouseUsed ();
	void Register_UnityEngine_GUIUtility_SetMouseUsed ();
	Register_UnityEngine_GUIUtility_SetMouseUsed ();
	void Register_UnityEngine_GUIUtility_SetKeyboardScriptInstanceID ();
	Register_UnityEngine_GUIUtility_SetKeyboardScriptInstanceID ();
	void Register_UnityEngine_GUIUtility_get_textFieldInput ();
	Register_UnityEngine_GUIUtility_get_textFieldInput ();
	void Register_UnityEngine_GUIUtility_set_textFieldInput ();
	Register_UnityEngine_GUIUtility_set_textFieldInput ();
	void Register_UnityEngine_IDList_Internal_SkipToControlID ();
	Register_UnityEngine_IDList_Internal_SkipToControlID ();
	void Register_UnityEngine_IDList_CalculateNextFromHintList ();
	Register_UnityEngine_IDList_CalculateNextFromHintList ();
	void Register_UnityEngine_IDList_ResetIdx ();
	Register_UnityEngine_IDList_ResetIdx ();
	void Register_UnityEngine_Input_GetButtonDown ();
	Register_UnityEngine_Input_GetButtonDown ();
	void Register_UnityEngine_Input_GetMouseButton ();
	Register_UnityEngine_Input_GetMouseButton ();
	void Register_UnityEngine_Input_get_mousePosition ();
	Register_UnityEngine_Input_get_mousePosition ();
	void Register_UnityEngine_Input_GetTouch ();
	Register_UnityEngine_Input_GetTouch ();
	void Register_UnityEngine_Input_get_touchCount ();
	Register_UnityEngine_Input_get_touchCount ();
	void Register_UnityEngine_Input_get_compositionString ();
	Register_UnityEngine_Input_get_compositionString ();
	void Register_UnityEngine_Input_INTERNAL_set_compositionCursorPos ();
	Register_UnityEngine_Input_INTERNAL_set_compositionCursorPos ();
	void Register_UnityEngine_iPhone_get_generation ();
	Register_UnityEngine_iPhone_get_generation ();
	void Register_UnityEngine_iPhoneInput_GetTouch ();
	Register_UnityEngine_iPhoneInput_GetTouch ();
	void Register_UnityEngine_iPhoneInput_get_touchCount ();
	Register_UnityEngine_iPhoneInput_get_touchCount ();
	void Register_UnityEngine_iPhoneInput_get_lastLocation ();
	Register_UnityEngine_iPhoneInput_get_lastLocation ();
	void Register_UnityEngine_iPhoneKeyboard_Destroy ();
	Register_UnityEngine_iPhoneKeyboard_Destroy ();
	void Register_UnityEngine_iPhoneKeyboard_set_autorotateToPortrait ();
	Register_UnityEngine_iPhoneKeyboard_set_autorotateToPortrait ();
	void Register_UnityEngine_iPhoneKeyboard_set_autorotateToPortraitUpsideDown ();
	Register_UnityEngine_iPhoneKeyboard_set_autorotateToPortraitUpsideDown ();
	void Register_UnityEngine_iPhoneKeyboard_set_autorotateToLandscapeLeft ();
	Register_UnityEngine_iPhoneKeyboard_set_autorotateToLandscapeLeft ();
	void Register_UnityEngine_iPhoneKeyboard_set_autorotateToLandscapeRight ();
	Register_UnityEngine_iPhoneKeyboard_set_autorotateToLandscapeRight ();
	void Register_UnityEngine_iPhoneSettings_set_screenCanDarken ();
	Register_UnityEngine_iPhoneSettings_set_screenCanDarken ();
	void Register_UnityEngine_iPhoneSettings_get_generation ();
	Register_UnityEngine_iPhoneSettings_get_generation ();
	void Register_UnityEngine_iPhoneSettings_get_locationServiceStatus ();
	Register_UnityEngine_iPhoneSettings_get_locationServiceStatus ();
	void Register_UnityEngine_iPhoneSettings_StartLocationServiceUpdates ();
	Register_UnityEngine_iPhoneSettings_StartLocationServiceUpdates ();
	void Register_UnityEngine_iPhoneSettings_StopLocationServiceUpdates ();
	Register_UnityEngine_iPhoneSettings_StopLocationServiceUpdates ();
	void Register_UnityEngine_Material_get_shader ();
	Register_UnityEngine_Material_get_shader ();
	void Register_UnityEngine_Material_INTERNAL_CALL_SetColor ();
	Register_UnityEngine_Material_INTERNAL_CALL_SetColor ();
	void Register_UnityEngine_Material_GetColor ();
	Register_UnityEngine_Material_GetColor ();
	void Register_UnityEngine_Material_SetTexture ();
	Register_UnityEngine_Material_SetTexture ();
	void Register_UnityEngine_Material_GetTexture ();
	Register_UnityEngine_Material_GetTexture ();
	void Register_UnityEngine_Material_INTERNAL_CALL_SetTextureOffset ();
	Register_UnityEngine_Material_INTERNAL_CALL_SetTextureOffset ();
	void Register_UnityEngine_Material_INTERNAL_CALL_SetTextureScale ();
	Register_UnityEngine_Material_INTERNAL_CALL_SetTextureScale ();
	void Register_UnityEngine_Material_Internal_CreateWithShader ();
	Register_UnityEngine_Material_Internal_CreateWithShader ();
	void Register_UnityEngine_Material_CopyPropertiesFromMaterial ();
	Register_UnityEngine_Material_CopyPropertiesFromMaterial ();
	void Register_UnityEngine_Mathf_IsPowerOfTwo ();
	Register_UnityEngine_Mathf_IsPowerOfTwo ();
	void Register_UnityEngine_Matrix4x4_INTERNAL_CALL_Inverse ();
	Register_UnityEngine_Matrix4x4_INTERNAL_CALL_Inverse ();
	void Register_UnityEngine_Matrix4x4_INTERNAL_CALL_TRS ();
	Register_UnityEngine_Matrix4x4_INTERNAL_CALL_TRS ();
	void Register_UnityEngine_Mesh_Internal_Create ();
	Register_UnityEngine_Mesh_Internal_Create ();
	void Register_UnityEngine_Mesh_INTERNAL_CALL_Clear ();
	Register_UnityEngine_Mesh_INTERNAL_CALL_Clear ();
	void Register_UnityEngine_Mesh_get_vertices ();
	Register_UnityEngine_Mesh_get_vertices ();
	void Register_UnityEngine_Mesh_set_vertices ();
	Register_UnityEngine_Mesh_set_vertices ();
	void Register_UnityEngine_Mesh_get_normals ();
	Register_UnityEngine_Mesh_get_normals ();
	void Register_UnityEngine_Mesh_set_normals ();
	Register_UnityEngine_Mesh_set_normals ();
	void Register_UnityEngine_Mesh_get_tangents ();
	Register_UnityEngine_Mesh_get_tangents ();
	void Register_UnityEngine_Mesh_set_tangents ();
	Register_UnityEngine_Mesh_set_tangents ();
	void Register_UnityEngine_Mesh_get_uv ();
	Register_UnityEngine_Mesh_get_uv ();
	void Register_UnityEngine_Mesh_set_uv ();
	Register_UnityEngine_Mesh_set_uv ();
	void Register_UnityEngine_Mesh_get_uv2 ();
	Register_UnityEngine_Mesh_get_uv2 ();
	void Register_UnityEngine_Mesh_set_uv2 ();
	Register_UnityEngine_Mesh_set_uv2 ();
	void Register_UnityEngine_Mesh_INTERNAL_get_bounds ();
	Register_UnityEngine_Mesh_INTERNAL_get_bounds ();
	void Register_UnityEngine_Mesh_INTERNAL_set_bounds ();
	Register_UnityEngine_Mesh_INTERNAL_set_bounds ();
	void Register_UnityEngine_Mesh_get_colors ();
	Register_UnityEngine_Mesh_get_colors ();
	void Register_UnityEngine_Mesh_set_colors ();
	Register_UnityEngine_Mesh_set_colors ();
	void Register_UnityEngine_Mesh_INTERNAL_CALL_RecalculateBounds ();
	Register_UnityEngine_Mesh_INTERNAL_CALL_RecalculateBounds ();
	void Register_UnityEngine_Mesh_INTERNAL_CALL_RecalculateNormals ();
	Register_UnityEngine_Mesh_INTERNAL_CALL_RecalculateNormals ();
	void Register_UnityEngine_Mesh_Optimize ();
	Register_UnityEngine_Mesh_Optimize ();
	void Register_UnityEngine_Mesh_get_triangles ();
	Register_UnityEngine_Mesh_get_triangles ();
	void Register_UnityEngine_Mesh_set_triangles ();
	Register_UnityEngine_Mesh_set_triangles ();
	void Register_UnityEngine_Mesh_GetTriangles ();
	Register_UnityEngine_Mesh_GetTriangles ();
	void Register_UnityEngine_Mesh_SetTriangles ();
	Register_UnityEngine_Mesh_SetTriangles ();
	void Register_UnityEngine_Mesh_SetTrianglesDontRebuildCollisionTriangles ();
	Register_UnityEngine_Mesh_SetTrianglesDontRebuildCollisionTriangles ();
	void Register_UnityEngine_Mesh_get_vertexCount ();
	Register_UnityEngine_Mesh_get_vertexCount ();
	void Register_UnityEngine_Mesh_get_subMeshCount ();
	Register_UnityEngine_Mesh_get_subMeshCount ();
	void Register_UnityEngine_Mesh_set_subMeshCount ();
	Register_UnityEngine_Mesh_set_subMeshCount ();
	void Register_UnityEngine_Mesh_SetTriangleStrip ();
	Register_UnityEngine_Mesh_SetTriangleStrip ();
	void Register_UnityEngine_Mesh_GetTriangleStrip ();
	Register_UnityEngine_Mesh_GetTriangleStrip ();
	void Register_UnityEngine_Mesh_CombineMeshes ();
	Register_UnityEngine_Mesh_CombineMeshes ();
	void Register_UnityEngine_Mesh_get_boneWeights ();
	Register_UnityEngine_Mesh_get_boneWeights ();
	void Register_UnityEngine_Mesh_set_boneWeights ();
	Register_UnityEngine_Mesh_set_boneWeights ();
	void Register_UnityEngine_Mesh_get_bindposes ();
	Register_UnityEngine_Mesh_get_bindposes ();
	void Register_UnityEngine_Mesh_set_bindposes ();
	Register_UnityEngine_Mesh_set_bindposes ();
	void Register_UnityEngine_MeshFilter_get_mesh ();
	Register_UnityEngine_MeshFilter_get_mesh ();
	void Register_UnityEngine_MonoBehaviour_StartCoroutine_Auto ();
	Register_UnityEngine_MonoBehaviour_StartCoroutine_Auto ();
	void Register_UnityEngine_MonoBehaviour_set_useGUILayout ();
	Register_UnityEngine_MonoBehaviour_set_useGUILayout ();
	void Register_UnityEngine_MonoBehaviour__ctor ();
	Register_UnityEngine_MonoBehaviour__ctor ();
	void Register_UnityEngine_Object_CompareBaseObjects ();
	Register_UnityEngine_Object_CompareBaseObjects ();
	void Register_UnityEngine_Object_Internal_CloneSingle ();
	Register_UnityEngine_Object_Internal_CloneSingle ();
	void Register_UnityEngine_Object_INTERNAL_CALL_Internal_InstantiateSingle ();
	Register_UnityEngine_Object_INTERNAL_CALL_Internal_InstantiateSingle ();
	void Register_UnityEngine_Object_Destroy ();
	Register_UnityEngine_Object_Destroy ();
	void Register_UnityEngine_Object_get_name ();
	Register_UnityEngine_Object_get_name ();
	void Register_UnityEngine_Object_set_name ();
	Register_UnityEngine_Object_set_name ();
	void Register_UnityEngine_Object_DontDestroyOnLoad ();
	Register_UnityEngine_Object_DontDestroyOnLoad ();
	void Register_UnityEngine_Object_ToString ();
	Register_UnityEngine_Object_ToString ();
	void Register_UnityEngine_Physics_INTERNAL_CALL_Internal_Raycast ();
	Register_UnityEngine_Physics_INTERNAL_CALL_Internal_Raycast ();
	void Register_UnityEngine_Physics_INTERNAL_CALL_RaycastAll ();
	Register_UnityEngine_Physics_INTERNAL_CALL_RaycastAll ();
	void Register_UnityEngine_PlayerPrefs_TrySetInt ();
	Register_UnityEngine_PlayerPrefs_TrySetInt ();
	void Register_UnityEngine_PlayerPrefs_TrySetFloat ();
	Register_UnityEngine_PlayerPrefs_TrySetFloat ();
	void Register_UnityEngine_PlayerPrefs_TrySetSetString ();
	Register_UnityEngine_PlayerPrefs_TrySetSetString ();
	void Register_UnityEngine_PlayerPrefs_GetInt ();
	Register_UnityEngine_PlayerPrefs_GetInt ();
	void Register_UnityEngine_PlayerPrefs_GetFloat ();
	Register_UnityEngine_PlayerPrefs_GetFloat ();
	void Register_UnityEngine_PlayerPrefs_GetString ();
	Register_UnityEngine_PlayerPrefs_GetString ();
	void Register_UnityEngine_QualitySettings_get_activeColorSpace ();
	Register_UnityEngine_QualitySettings_get_activeColorSpace ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_AngleAxis ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_AngleAxis ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_FromToRotation ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_FromToRotation ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_LookRotation ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_LookRotation ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Inverse ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Inverse ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_ToEulerRad ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_ToEulerRad ();
	void Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_FromEulerRad ();
	Register_UnityEngine_Quaternion_INTERNAL_CALL_Internal_FromEulerRad ();
	void Register_UnityEngine_Random_set_seed ();
	Register_UnityEngine_Random_set_seed ();
	void Register_UnityEngine_Random_Range ();
	Register_UnityEngine_Random_Range ();
	void Register_UnityEngine_Random_RandomRangeInt ();
	Register_UnityEngine_Random_RandomRangeInt ();
	void Register_UnityEngine_Random_get_value ();
	Register_UnityEngine_Random_get_value ();
	void Register_UnityEngine_Renderer_set_enabled ();
	Register_UnityEngine_Renderer_set_enabled ();
	void Register_UnityEngine_Renderer_get_material ();
	Register_UnityEngine_Renderer_get_material ();
	void Register_UnityEngine_Renderer_set_material ();
	Register_UnityEngine_Renderer_set_material ();
	void Register_UnityEngine_Renderer_get_sharedMaterial ();
	Register_UnityEngine_Renderer_get_sharedMaterial ();
	void Register_UnityEngine_Renderer_get_materials ();
	Register_UnityEngine_Renderer_get_materials ();
	void Register_UnityEngine_Renderer_get_bounds ();
	Register_UnityEngine_Renderer_get_bounds ();
	void Register_UnityEngine_RenderTexture_Internal_CreateRenderTexture ();
	Register_UnityEngine_RenderTexture_Internal_CreateRenderTexture ();
	void Register_UnityEngine_RenderTexture_Internal_GetWidth ();
	Register_UnityEngine_RenderTexture_Internal_GetWidth ();
	void Register_UnityEngine_RenderTexture_Internal_SetWidth ();
	Register_UnityEngine_RenderTexture_Internal_SetWidth ();
	void Register_UnityEngine_RenderTexture_Internal_GetHeight ();
	Register_UnityEngine_RenderTexture_Internal_GetHeight ();
	void Register_UnityEngine_RenderTexture_Internal_SetHeight ();
	Register_UnityEngine_RenderTexture_Internal_SetHeight ();
	void Register_UnityEngine_RenderTexture_Internal_SetSRGBReadWrite ();
	Register_UnityEngine_RenderTexture_Internal_SetSRGBReadWrite ();
	void Register_UnityEngine_RenderTexture_set_depth ();
	Register_UnityEngine_RenderTexture_set_depth ();
	void Register_UnityEngine_RenderTexture_set_isPowerOfTwo ();
	Register_UnityEngine_RenderTexture_set_isPowerOfTwo ();
	void Register_UnityEngine_RenderTexture_set_format ();
	Register_UnityEngine_RenderTexture_set_format ();
	void Register_UnityEngine_RenderTexture_set_active ();
	Register_UnityEngine_RenderTexture_set_active ();
	void Register_UnityEngine_Resources_Load ();
	Register_UnityEngine_Resources_Load ();
	void Register_UnityEngine_Resources_UnloadUnusedAssets ();
	Register_UnityEngine_Resources_UnloadUnusedAssets ();
	void Register_UnityEngine_Rigidbody_INTERNAL_set_velocity ();
	Register_UnityEngine_Rigidbody_INTERNAL_set_velocity ();
	void Register_UnityEngine_Screen_get_width ();
	Register_UnityEngine_Screen_get_width ();
	void Register_UnityEngine_Screen_get_height ();
	Register_UnityEngine_Screen_get_height ();
	void Register_UnityEngine_ScriptableObject__ctor ();
	Register_UnityEngine_ScriptableObject__ctor ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticate ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticate ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticated ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Authenticated ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserName ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserName ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserID ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserID ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Underage ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_Underage ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserImage ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_UserImage ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadFriends ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadFriends ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievementDescriptions ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievementDescriptions ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievements ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadAchievements ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportProgress ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportProgress ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportScore ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ReportScore ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadScores ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadScores ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowAchievementsUI ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowAchievementsUI ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowLeaderboardUI ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowLeaderboardUI ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadUsers ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_LoadUsers ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ResetAllAchievements ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ResetAllAchievements ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowDefaultAchievementBanner ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GameCenterPlatform_Internal_ShowDefaultAchievementBanner ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScores ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScores ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScoresWithUsers ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Internal_LoadScoresWithUsers ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Loading ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Loading ();
	void Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Dispose ();
	Register_UnityEngine_SocialPlatforms_GameCenter_GcLeaderboard_Dispose ();
	void Register_UnityEngine_TextAsset_get_text ();
	Register_UnityEngine_TextAsset_get_text ();
	void Register_UnityEngine_TextAsset_get_bytes ();
	Register_UnityEngine_TextAsset_get_bytes ();
	void Register_UnityEngine_TextMesh_set_text ();
	Register_UnityEngine_TextMesh_set_text ();
	void Register_UnityEngine_Texture_Internal_GetWidth ();
	Register_UnityEngine_Texture_Internal_GetWidth ();
	void Register_UnityEngine_Texture_Internal_GetHeight ();
	Register_UnityEngine_Texture_Internal_GetHeight ();
	void Register_UnityEngine_Texture_set_mipMapBias ();
	Register_UnityEngine_Texture_set_mipMapBias ();
	void Register_UnityEngine_Texture_GetNativeTextureID ();
	Register_UnityEngine_Texture_GetNativeTextureID ();
	void Register_UnityEngine_Texture2D_Internal_Create ();
	Register_UnityEngine_Texture2D_Internal_Create ();
	void Register_UnityEngine_Texture2D_INTERNAL_CALL_SetPixel ();
	Register_UnityEngine_Texture2D_INTERNAL_CALL_SetPixel ();
	void Register_UnityEngine_Texture2D_GetPixel ();
	Register_UnityEngine_Texture2D_GetPixel ();
	void Register_UnityEngine_Texture2D_LoadImage ();
	Register_UnityEngine_Texture2D_LoadImage ();
	void Register_UnityEngine_Texture2D_Apply ();
	Register_UnityEngine_Texture2D_Apply ();
	void Register_UnityEngine_Texture2D_INTERNAL_CALL_ReadPixels ();
	Register_UnityEngine_Texture2D_INTERNAL_CALL_ReadPixels ();
	void Register_UnityEngine_Time_get_time ();
	Register_UnityEngine_Time_get_time ();
	void Register_UnityEngine_Time_get_timeSinceLevelLoad ();
	Register_UnityEngine_Time_get_timeSinceLevelLoad ();
	void Register_UnityEngine_Time_get_deltaTime ();
	Register_UnityEngine_Time_get_deltaTime ();
	void Register_UnityEngine_Time_get_timeScale ();
	Register_UnityEngine_Time_get_timeScale ();
	void Register_UnityEngine_Time_get_realtimeSinceStartup ();
	Register_UnityEngine_Time_get_realtimeSinceStartup ();
	void Register_UnityEngine_TouchScreenKeyboard_Destroy ();
	Register_UnityEngine_TouchScreenKeyboard_Destroy ();
	void Register_UnityEngine_TouchScreenKeyboard_TouchScreenKeyboard_InternalConstructorHelper ();
	Register_UnityEngine_TouchScreenKeyboard_TouchScreenKeyboard_InternalConstructorHelper ();
	void Register_UnityEngine_TouchScreenKeyboard_get_text ();
	Register_UnityEngine_TouchScreenKeyboard_get_text ();
	void Register_UnityEngine_TouchScreenKeyboard_get_done ();
	Register_UnityEngine_TouchScreenKeyboard_get_done ();
	void Register_UnityEngine_Transform_INTERNAL_get_position ();
	Register_UnityEngine_Transform_INTERNAL_get_position ();
	void Register_UnityEngine_Transform_INTERNAL_set_position ();
	Register_UnityEngine_Transform_INTERNAL_set_position ();
	void Register_UnityEngine_Transform_INTERNAL_get_localPosition ();
	Register_UnityEngine_Transform_INTERNAL_get_localPosition ();
	void Register_UnityEngine_Transform_INTERNAL_set_localPosition ();
	Register_UnityEngine_Transform_INTERNAL_set_localPosition ();
	void Register_UnityEngine_Transform_INTERNAL_get_localEulerAngles ();
	Register_UnityEngine_Transform_INTERNAL_get_localEulerAngles ();
	void Register_UnityEngine_Transform_INTERNAL_set_localEulerAngles ();
	Register_UnityEngine_Transform_INTERNAL_set_localEulerAngles ();
	void Register_UnityEngine_Transform_INTERNAL_get_rotation ();
	Register_UnityEngine_Transform_INTERNAL_get_rotation ();
	void Register_UnityEngine_Transform_INTERNAL_set_rotation ();
	Register_UnityEngine_Transform_INTERNAL_set_rotation ();
	void Register_UnityEngine_Transform_INTERNAL_get_localRotation ();
	Register_UnityEngine_Transform_INTERNAL_get_localRotation ();
	void Register_UnityEngine_Transform_INTERNAL_set_localRotation ();
	Register_UnityEngine_Transform_INTERNAL_set_localRotation ();
	void Register_UnityEngine_Transform_INTERNAL_get_localScale ();
	Register_UnityEngine_Transform_INTERNAL_get_localScale ();
	void Register_UnityEngine_Transform_INTERNAL_set_localScale ();
	Register_UnityEngine_Transform_INTERNAL_set_localScale ();
	void Register_UnityEngine_Transform_get_parent ();
	Register_UnityEngine_Transform_get_parent ();
	void Register_UnityEngine_Transform_set_parent ();
	Register_UnityEngine_Transform_set_parent ();
	void Register_UnityEngine_Transform_INTERNAL_get_worldToLocalMatrix ();
	Register_UnityEngine_Transform_INTERNAL_get_worldToLocalMatrix ();
	void Register_UnityEngine_Transform_INTERNAL_get_localToWorldMatrix ();
	Register_UnityEngine_Transform_INTERNAL_get_localToWorldMatrix ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_LookAt ();
	Register_UnityEngine_Transform_INTERNAL_CALL_LookAt ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_TransformDirection ();
	Register_UnityEngine_Transform_INTERNAL_CALL_TransformDirection ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformDirection ();
	Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformDirection ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_TransformPoint ();
	Register_UnityEngine_Transform_INTERNAL_CALL_TransformPoint ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformPoint ();
	Register_UnityEngine_Transform_INTERNAL_CALL_InverseTransformPoint ();
	void Register_UnityEngine_Transform_get_root ();
	Register_UnityEngine_Transform_get_root ();
	void Register_UnityEngine_Transform_get_childCount ();
	Register_UnityEngine_Transform_get_childCount ();
	void Register_UnityEngine_Transform_DetachChildren ();
	Register_UnityEngine_Transform_DetachChildren ();
	void Register_UnityEngine_Transform_Find ();
	Register_UnityEngine_Transform_Find ();
	void Register_UnityEngine_Transform_INTERNAL_get_lossyScale ();
	Register_UnityEngine_Transform_INTERNAL_get_lossyScale ();
	void Register_UnityEngine_Transform_IsChildOf ();
	Register_UnityEngine_Transform_IsChildOf ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_RotateAround ();
	Register_UnityEngine_Transform_INTERNAL_CALL_RotateAround ();
	void Register_UnityEngine_Transform_INTERNAL_CALL_RotateAroundLocal ();
	Register_UnityEngine_Transform_INTERNAL_CALL_RotateAroundLocal ();
	void Register_UnityEngine_Transform_GetChild ();
	Register_UnityEngine_Transform_GetChild ();
	void Register_UnityEngine_Transform_GetChildCount ();
	Register_UnityEngine_Transform_GetChildCount ();
	void Register_UnityEngine_UnityLogWriter_WriteStringToUnityLog ();
	Register_UnityEngine_UnityLogWriter_WriteStringToUnityLog ();
	void Register_UnityEngine_WWW_DestroyWWW ();
	Register_UnityEngine_WWW_DestroyWWW ();
	void Register_UnityEngine_WWW_InitWWW ();
	Register_UnityEngine_WWW_InitWWW ();
	void Register_UnityEngine_WWW_get_responseHeadersString ();
	Register_UnityEngine_WWW_get_responseHeadersString ();
	void Register_UnityEngine_WWW_get_bytes ();
	Register_UnityEngine_WWW_get_bytes ();
	void Register_UnityEngine_WWW_get_error ();
	Register_UnityEngine_WWW_get_error ();
	void Register_UnityEngine_WWW_GetTexture ();
	Register_UnityEngine_WWW_GetTexture ();
	void Register_UnityEngine_WWW_get_isDone ();
	Register_UnityEngine_WWW_get_isDone ();

}
void RegisterAllClasses() 
{
void RegisterMaximumClassID ();
 RegisterMaximumClassID();
int RegisterClass_GameObject();
 RegisterClass_GameObject();
int RegisterClass_Component();
 RegisterClass_Component();
int RegisterClass_LevelGameManager();
 RegisterClass_LevelGameManager();
int RegisterClass_Transform();
 RegisterClass_Transform();
int RegisterClass_Behaviour();
 RegisterClass_Behaviour();
int RegisterClass_GameManager();
 RegisterClass_GameManager();
int RegisterClass_ParticleAnimator();
 RegisterClass_ParticleAnimator();
int RegisterClass_EllipsoidParticleEmitter();
 RegisterClass_EllipsoidParticleEmitter();
int RegisterClass_EditorExtension();
 RegisterClass_EditorExtension();
int RegisterClass_Camera();
 RegisterClass_Camera();
int RegisterClass_Material();
 RegisterClass_Material();
int RegisterClass_MeshRenderer();
 RegisterClass_MeshRenderer();
int RegisterClass_Renderer();
 RegisterClass_Renderer();
int RegisterClass_ParticleRenderer();
 RegisterClass_ParticleRenderer();
int RegisterClass_Texture();
 RegisterClass_Texture();
int RegisterClass_Texture2D();
 RegisterClass_Texture2D();
int RegisterClass_Scene();
 RegisterClass_Scene();
int RegisterClass_MeshFilter();
 RegisterClass_MeshFilter();
int RegisterClass_Mesh();
 RegisterClass_Mesh();
int RegisterClass_Shader();
 RegisterClass_Shader();
int RegisterClass_TextAsset();
 RegisterClass_TextAsset();
int RegisterClass_Rigidbody();
 RegisterClass_Rigidbody();
int RegisterClass_Collider();
 RegisterClass_Collider();
int RegisterClass_MeshCollider();
 RegisterClass_MeshCollider();
int RegisterClass_BoxCollider();
 RegisterClass_BoxCollider();
int RegisterClass_AnimationClip();
 RegisterClass_AnimationClip();
int RegisterClass_AudioListener();
 RegisterClass_AudioListener();
int RegisterClass_AudioSource();
 RegisterClass_AudioSource();
int RegisterClass_AudioClip();
 RegisterClass_AudioClip();
int RegisterClass_RenderTexture();
 RegisterClass_RenderTexture();
int RegisterClass_ParticleEmitter();
 RegisterClass_ParticleEmitter();
int RegisterClass_GUILayer();
 RegisterClass_GUILayer();
int RegisterClass_TextMesh();
 RegisterClass_TextMesh();
int RegisterClass_RenderSettings();
 RegisterClass_RenderSettings();
int RegisterClass_Light();
 RegisterClass_Light();
int RegisterClass_Animation();
 RegisterClass_Animation();
int RegisterClass_MonoBehaviour();
 RegisterClass_MonoBehaviour();
int RegisterClass_MonoScript();
 RegisterClass_MonoScript();
int RegisterClass_FlareLayer();
 RegisterClass_FlareLayer();
int RegisterClass_HaloManager();
 RegisterClass_HaloManager();
int RegisterClass_Font();
 RegisterClass_Font();
int RegisterClass_NamedObject();
 RegisterClass_NamedObject();
int RegisterClass_GUIText();
 RegisterClass_GUIText();
int RegisterClass_GUIElement();
 RegisterClass_GUIElement();
int RegisterClass_CapsuleCollider();
 RegisterClass_CapsuleCollider();
int RegisterClass_SkinnedMeshRenderer();
 RegisterClass_SkinnedMeshRenderer();
int RegisterClass_LightmapSettings();
 RegisterClass_LightmapSettings();
int RegisterClass_AudioBehaviour();
 RegisterClass_AudioBehaviour();
int RegisterClass_NavMeshSettings();
 RegisterClass_NavMeshSettings();
int RegisterClass_PreloadData();
 RegisterClass_PreloadData();
int RegisterClass_Cubemap();
 RegisterClass_Cubemap();
int RegisterClass_LODGroup();
 RegisterClass_LODGroup();
int RegisterClass_PhysicsManager();
 RegisterClass_PhysicsManager();
int RegisterClass_TimeManager();
 RegisterClass_TimeManager();
int RegisterClass_AudioManager();
 RegisterClass_AudioManager();
int RegisterClass_InputManager();
 RegisterClass_InputManager();
int RegisterClass_RenderManager();
 RegisterClass_RenderManager();
int RegisterClass_QualitySettings();
 RegisterClass_QualitySettings();
int RegisterClass_NotificationManager();
 RegisterClass_NotificationManager();
int RegisterClass_AnimationManager();
 RegisterClass_AnimationManager();
int RegisterClass_TagManager();
 RegisterClass_TagManager();
int RegisterClass_ScriptMapper();
 RegisterClass_ScriptMapper();
int RegisterClass_DelayedCallManager();
 RegisterClass_DelayedCallManager();
int RegisterClass_MonoManager();
 RegisterClass_MonoManager();
int RegisterClass_NavMeshLayers();
 RegisterClass_NavMeshLayers();
int RegisterClass_PlayerSettings();
 RegisterClass_PlayerSettings();
int RegisterClass_BuildSettings();
 RegisterClass_BuildSettings();
int RegisterClass_ResourceManager();
 RegisterClass_ResourceManager();
int RegisterClass_MasterServerInterface();
 RegisterClass_MasterServerInterface();
int RegisterClass_AssetBundle();
 RegisterClass_AssetBundle();
int RegisterClass_CharacterController();
 RegisterClass_CharacterController();
int RegisterClass_ConstantForce();
 RegisterClass_ConstantForce();
int RegisterClass_GUITexture();
 RegisterClass_GUITexture();
int RegisterClass_HingeJoint();
 RegisterClass_HingeJoint();
int RegisterClass_Joint();
 RegisterClass_Joint();
int RegisterClass_NetworkView();
 RegisterClass_NetworkView();
int RegisterClass_NetworkManager();
 RegisterClass_NetworkManager();

}
